#include <iostream>
#include <wiringPi.h>

#include "Gestion74HCT595.h"
#include "GestionPinGPIO.h"

using namespace std;

Gestion74HCT595 circuit(GPIO14, GPIO15, GPIO18, true);

int main() {
	char val[10];
	cout << "1" << endl;
	circuit.write(true);
	circuit.scroll();
	circuit.latch();
	cin >> val;
	cout << "2" << endl;
	circuit.write(false);
	circuit.scroll();
	circuit.latch();
	cin >> val;
	cout << "3" << endl;
	circuit.write(true);
	circuit.scroll();
	circuit.latch();
	cin >> val;
	cout << "4" << endl;
	circuit.write(false);
	circuit.scroll();
	circuit.latch();
	cin >> val;
	cout << "5" << endl;
	circuit.write(true);
	circuit.scroll();
	circuit.latch();
	cin >> val;
	cout << "6" << endl;
	circuit.write(false);
	circuit.scroll();
	circuit.latch();
	cin >> val;
	cout << "7" << endl;
	circuit.write(true);
	circuit.scroll();
	circuit.latch();
	cin >> val;
	cout << "8" << endl;
	circuit.write(false);
	circuit.scroll();
	circuit.latch();
	cin >> val;
	cout << "9" << endl;
	circuit.write((uint8_t)0xFF);
	cin >> val;
	cout << "10" << endl;
	circuit.write((uint8_t)0x00);
	cin >> val;
	cout << "11" << endl;
	circuit.write((uint8_t)0b10101010);
	cin >> val;
	cout << "12" << endl;
	circuit.write((uint8_t)0b01010101);
	cin >> val;
	cout << "13" << endl;
	circuit.write('a');
	cin >> val;
	cout << "14" << endl;
	circuit.write('Z');
	cin >> val;
	cout << "15" << endl;
	circuit.hight(PinHight0);
	cin >> val;
	cout << "16" << endl;
	circuit.hight(PinHight1);
	cin >> val;
	cout << "17" << endl;
	circuit.hight(PinHight2);
	cin >> val;
	cout << "18" << endl;
	circuit.hight(PinHight3);
	cin >> val;
	cout << "19" << endl;
	circuit.hight(PinHight4);
	cin >> val;
	cout << "20" << endl;
	circuit.hight(PinHight5);
	cin >> val;
	cout << "21" << endl;
	circuit.hight(PinHight6);
	cin >> val;
	cout << "22" << endl;
	circuit.hight(PinHight7);
	cin >> val;
	cout << "23" << endl;
	circuit.low(PinLow0);
	cin >> val;
	cout << "24" << endl;
	circuit.low(PinLow1);
	cin >> val;
	cout << "25" << endl;
	circuit.low(PinLow2);
	cin >> val;
	cout << "26" << endl;
	circuit.low(PinLow3);
	cin >> val;
	cout << "27" << endl;
	circuit.low(PinLow4);
	cin >> val;
	cout << "28" << endl;
	circuit.low(PinLow5);
	cin >> val;
	cout << "29" << endl;
	circuit.low(PinLow6);
	cin >> val;
	cout << "30" << endl;
	circuit.low(PinLow7);
	cin >> val;
	cout << "31" << endl;
	circuit.write((uint8_t)0xFF);
	cin >> val;
	cout << "32" << endl;
	circuit.write((uint8_t)0x00);
}
